Convert xy to lonlat #9
LexxPluss/JOSMPlugin pull request #11
Opened 2021-06-10 13:20 UTC by mach0330

Exporterに、PicLayerの画像の座標変換情報を出力する変更を追加。
新規にピクセル座標から緯度経度座標に変換するImporter Pluginを作成。

2021-06-10 18:06 UTC, kokosabu requested changes

2021-06-10 18:06 UTC, kokosabu commented on LexxPlussImporter/src/org/openstreetmap/josm/plugins/lexxpluss/io/LexxPlussReader.java
> +	 * 関数をそのままコピーしているだけで、特に変更は加えていない。
元のコードがどれか明示したいです。
以下であっているでしょうか?
https://github.com/openstreetmap/josm/blob/597cab135f3dad3569b1c273162910a0af88bb8e/src/org/openstreetmap/josm/io/OsmReader.java

2021-06-10 18:06 UTC, kokosabu commented on LexxPlussImporter/src/org/openstreetmap/josm/plugins/lexxpluss/io/LexxPlussReader.java
> +        try {
インデントが揃っていない部分が見受けられます。
タブ文字と空白文字が混在しているのが要因の一つに見えます。

2021-06-12 12:11 UTC, mach0330 commented on LexxPlussImporter/src/org/openstreetmap/josm/plugins/lexxpluss/io/LexxPlussReader.java
> +	 * 関数をそのままコピーしているだけで、特に変更は加えていない。
合っています。コメントの中に、上記のURLを記載しました。

2021-06-12 12:12 UTC, mach0330 commented on LexxPlussImporter/src/org/openstreetmap/josm/plugins/lexxpluss/io/LexxPlussReader.java
> +        try {
失礼しました。私的部分を含め、ファイル内すべてをタブで統一しました。

2021-06-12 14:23 UTC, kokosabu approved these changes

2021-06-12 14:23 UTC, merged