[#15] update: change coordinate precision
LexxPluss/JOSMPlugin pull request #16
Opened 2022-08-22 06:19 UTC by iida02

イシュー
https://github.com/LexxPluss/JOSMPlugin/issues/15

変更についての説明
https://github.com/LexxPluss/JOSMPlugin/issues/15#issuecomment-1221884421

2022-08-22 06:23 UTC, kokosabu approved these changes

2022-09-08 08:26 UTC, remmaTech12 commented
変更点は問題ないと思いました。
```
                  // 浮動小数点による誤差への対処
                  x = Math.floor(x * 1000000) / 1000000;
                  y = Math.floor(y * 1000000) / 1000000;                                            
```

インデントがずれて、全ての行が diff になってしまっているのが気になります...。

2022-09-08 08:28 UTC, remmaTech12 requested changes
すべての行が diff になっていて差分がわかりにくいので、インデントの変更が意図的でなければ修正お願いします。

2022-09-13 04:14 UTC, remmaTech12 commented
@iida02 
この変更を適用すると、osmファイルで多少位置を変えたときに、こんな感じでdiffが現れなくなるのかなと予想しています。
```
-    <tag k='pic_offset_x' v='1565.501' />
-    <tag k='pic_offset_y' v='68.50100000076517' />
-    <tag k='pixel_per_en_x' v='1.0799693591877784' />
-    <tag k='pixel_per_en_y' v='1.0799693591877786' />
-    <tag k='scaleX' v='0.09259521962293313' />
-    <tag k='scaleY' v='0.0925952197519934' />
+    <tag k='pic_offset_x' v='331.50100000000003' />
+    <tag k='pic_offset_y' v='41.50100000025747' />
+    <tag k='pixel_per_en_x' v='0.36368803763107366' />
+    <tag k='pixel_per_en_y' v='0.36368803763107366' />
+    <tag k='scaleX' v='0.2749609270939811' />
+    <tag k='scaleY' v='0.27496092747722484' />
```

本ブランチの変更を適用して[このページ](https://github.com/LexxPluss/JOSMPlugin/tree/master/LexxPlussExporter)で書かれている手順（以下）に従ってlexxpluss.jarを生成し、このプラグインをjosmで読み込んでみたのですが上記のdiffになってしまいました。
```
$ cd ~
$ git clone git@github.com:LexxPluss/JOSMPlugin.git
$ mv ~/JOSMPlugin/LexxPlussExporter ~/workspace/josm/plugins
$ cd ~/workspace/josm/plugins/PicLayer
$ ant # PicLayerがビルド済みでPicLayer.jarができている必要がある
$ sudo update-alternatives --config java  # java-11-openjdk-amd64 を選択( josm本体はJav11でビルドする必要があるらしい )
$ sudo update-alternatives --config javac  # java-11-openjdk-amd64 を選択( josm本体はJava11でビルドする必要があるらしい )
$ export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
$ cd ~/workspace/josm/plugins/LexxPlussExporter
$ ant install
```

何か手順間違っていますでしょうか？

2022-09-13 06:37 UTC, iida02 commented
@remmaTech12 
全部が差分として見えてしまう件は私の環境でも当時発生していたのですが、手元のVSCodeで比較した際には差分が出なかった（今回の変更箇所以外）ので、実害はないと判断しそのままにしてしまっていました。
今回、松田さんからの指摘により改めて原因を調べたところ、改行コードに差分があることが分かりました。（添付はcode-eolという拡張機能を入れて改行コードを可視化しています）
変更前のコードはCR/LFであり、Windows環境でコーディングされていた可能性があると思います。
さらに調べたらimporterのほうはLFで書かれていて、exporterはCR/LFで書かれていました。
今回exporterの変更なので同じexporter内の他のソースと統一するためにCR/LFに戻したほうがややこしくないかも知れませんね。
のちほど修正します。
![2022-09-13_14h53_24](https://user-images.githubusercontent.com/34387639/189821314-4251b647-eecb-48c2-a651-e532b31ba12d.png)

2022-09-13 06:56 UTC, iida02 commented
@remmaTech12 
改行コードをもとに戻す変更をプッシュしました。
ご指摘ありがとうございました。

2022-09-21 10:41 UTC, iida02 commented
@remmaTech12 
松田さんのレビューステータスが「request changes」になっています。
「Merge pull request」のボタンは有効になっているのでマージ可能だとは思いますが、念のため承認頂いたほうがよい（？）と思うので承認お願いたします。

2022-09-22 14:03 UTC, remmaTech12 commented
> 松田さんのレビューステータスが「request changes」になっています。

動作確認をして私の環境で動かなかったので、質問したところで止まっていました。
[この質問](https://github.com/LexxPluss/JOSMPlugin/pull/16#issuecomment-1244874675)お答えいただけますか？

2022-09-26 02:17 UTC, iida02 commented
> > 松田さんのレビューステータスが「request changes」になっています。
> 
> 動作確認をして私の環境で動かなかったので、質問したところで止まっていました。 [この質問](https://github.com/LexxPluss/JOSMPlugin/pull/16#issuecomment-1244874675)お答えいただけますか？

すみません、改行コード変更により勝手に解決したと思い込んでおりました。
よろしければ、のちほどF2Fで画面を見ながら問題の状況を確認させていただけないでしょうか。
@remmaTech12

2022-09-26 06:36 UTC, remmaTech12 approved these changes

2022-09-26 06:49 UTC, merged